column_width = 160
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
continuation_indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
align_call_args = false
align_chain = false
collapse_simple_statement = "Never"
indent_table = true
collapse_simple_table = "Never"
trailing_comma = "Always"
