return {
  { 'folke/tokyonight.nvim', enabled = true, lazy = false, priority = 1000 },
  { 'catppuccin/nvim', name = 'catppuccin', enabled = true, lazy = false },
  { 'webhooked/oscura.nvim', enabled = false, lazy = false, opts = {} },
  { 'Mofiqul/vscode.nvim', enabled = true, lazy = false, opts = {} },
  { 'slugbyte/lackluster.nvim', enabled = false, lazy = true, opts = {} },
  { 'projekt0n/github-nvim-theme', enabled = true, lazy = false },
  { 'forest-nvim/sequoia.nvim', enabled = true, lazy = false },
  { 'shaunsingh/nord.nvim', enabled = true, lazy = false },
  { 'EdenEast/nightfox.nvim', enabled = true, lazy = false },
  { 'p00f/alabaster.nvim', enabled = false, lazy = false },
  {
    'armannikoyan/rusty',
    enabled = false,
    lazy = false,
    opts = { transparent = true, italic_comments = true, underline_current_line = true },
  },
  { 'oxfist/night-owl.nvim', enabled = true, lazy = false, opts = {} },
  { 'rebelot/kanagawa.nvim', enabled = true, lazy = false, opts = {} },
  { 'olimorris/onedarkpro.nvim', enabled = true, lazy = false },
  { 'sainnhe/everforest', enabled = false, lazy = false },
  { 'rose-pine/neovim', enabled = true, lazy = false, name = 'rose-pine' },
  { 'Mofiqul/dracula.nvim', enabled = true, lazy = false, opts = {} },

  { -- color html colors
    'NvChad/nvim-colorizer.lua',
    enabled = true,
    opts = {
      filetypes = { 'html', 'css', 'javascript', 'javascriptreact', 'typescript', 'typescriptreact', 'vue', 'svelte', 'astro' },
      user_default_options = {
        RGB = true,
        RRGGBB = true,
        names = true,
        RRGGBBAA = true,
        AARRGGBB = false,
        rgb_fn = false,
        hsl_fn = false,
        css = false,
        css_fn = false,
        mode = 'background',
        tailwind = false,
        sass = { enable = false, parsers = { 'css' } },
        virtualtext = '■',
        always_update = false,
      },
      buftypes = {},
    },
  },
}
