return {
    { 'folke/tokyonight.nvim', enabled = true, lazy = false, priority = 1000 },
    { 'catppuccin/nvim', name = 'catppuccin', enabled = false, lazy = false, priority = 1000 },
    { 'webhooked/oscura.nvim', enabled = false, lazy = false, priority = 1000, opts = {} },
    { 'Mofiqul/vscode.nvim', enabled = false, lazy = false, priority = 1000, opts = {} },
    { 'slugbyte/lackluster.nvim', enabled = false, lazy = false, priority = 1000, opts = {} },
    { 'projekt0n/github-nvim-theme', enabled = false, lazy = false, priority = 1000 },
    { 'forest-nvim/sequoia.nvim', enabled = false, lazy = false, priority = 1000 },
    { 'shaunsingh/nord.nvim', enabled = false, lazy = false, priority = 1000 },
    { 'EdenEast/nightfox.nvim', enabled = false, lazy = false, priority = 1000 },
    { 'p00f/alabaster.nvim', enabled = false, lazy = false, priority = 1000 },
    {
        'armannikoyan/rusty',
        enabled = false,
        lazy = false,
        priority = 1000,
        opts = { transparent = true, italic_comments = true, underline_current_line = true },
    },
    { 'oxfist/night-owl.nvim', enabled = false, lazy = false, priority = 1000, opts = {} },
    { 'rebelot/kanagawa.nvim', enabled = false, lazy = false, priority = 1000, opts = {} },
    { 'olimorris/onedarkpro.nvim', enabled = false, lazy = false, priority = 1000 },
    { 'sainnhe/everforest', enabled = false, lazy = false, priority = 1000 },
    { 'rose-pine/neovim', enabled = true, lazy = false, priority = 1000, name = 'rose-pine' },

    { -- color html colors
        'NvChad/nvim-colorizer.lua',
        enabled = true,
        opts = {
            filetypes = { 'html', 'css', 'javascript', 'javascriptreact', 'typescript', 'typescriptreact', 'vue', 'svelte', 'astro' },
            user_default_options = {
                RGB = true,
                RRGGBB = true,
                names = true,
                RRGGBBAA = true,
                AARRGGBB = false,
                rgb_fn = false,
                hsl_fn = false,
                css = false,
                css_fn = false,
                mode = 'background',
                tailwind = false,
                sass = { enable = false, parsers = { 'css' } },
                virtualtext = '■',
                always_update = false,
            },
            buftypes = {},
        },
    },
}
